name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      ENABLE_SOURCE_MAPS: '1'
      SOURCE_MAP_UPLOAD_PROVIDER: newrelic
      NEW_RELIC_USER_API_KEY: ${{ secrets.NEW_RELIC_USER_API_KEY }}
      NEW_RELIC_BROWSER_APP_ID: ${{ secrets.NEW_RELIC_BROWSER_APP_ID }}
      NEXT_PUBLIC_NEW_RELIC_BROWSER_APP_ID: ${{ secrets.NEXT_PUBLIC_NEW_RELIC_BROWSER_APP_ID }}
      NEW_RELIC_SOURCE_MAP_BASE_URL: ${{ secrets.NEW_RELIC_SOURCE_MAP_BASE_URL }}
      NEW_RELIC_SOURCE_MAP_RELEASE: ${{ secrets.NEW_RELIC_SOURCE_MAP_RELEASE }}
      NEW_RELIC_REGION: ${{ secrets.NEW_RELIC_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and export static site
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          # Inject GitHub variable into the Next.js build
          NEXT_PUBLIC_ANALYTICS_WORKER_URL: ${{ vars.NEXT_PUBLIC_ANALYTICS_WORKER_URL }}
          NEXT_PUBLIC_OBSERVABILITY_ENABLED: ${{ vars.NEXT_PUBLIC_OBSERVABILITY_ENABLED }}
          NEXT_PUBLIC_HDX_API_KEY: ${{ vars.NEXT_PUBLIC_HDX_API_KEY }}
          NEXT_PUBLIC_HDX_HOST: ${{ vars.NEXT_PUBLIC_HDX_HOST }}
          NEXT_PUBLIC_HDX_SERVICE_NAME: ${{ vars.NEXT_PUBLIC_HDX_SERVICE_NAME }}
          NEXT_PUBLIC_APP_ENV: ${{ vars.NEXT_PUBLIC_APP_ENV }}
          # Force basePath for GitHub Project Pages (e.g., /<repo>)
          # next.config.mjs reads BASE_PATH (or NEXT_PUBLIC_BASE_PATH) with priority
          BASE_PATH: /${{ github.event.repository.name }}
        run: |
          echo "NEXT_PUBLIC_ANALYTICS_WORKER_URL=${NEXT_PUBLIC_ANALYTICS_WORKER_URL}"
          echo "NEXT_PUBLIC_OBSERVABILITY_ENABLED=${NEXT_PUBLIC_OBSERVABILITY_ENABLED}"
          echo "NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}"
          echo "BASE_PATH=${BASE_PATH}"
          pnpm build
          # For older Next versions, export step is required. Harmless if not needed.
          npx next export || true

      - name: Upload source maps to New Relic
        continue-on-error: true
        if: ${{ env.NEW_RELIC_USER_API_KEY != '' && env.NEW_RELIC_SOURCE_MAP_BASE_URL != '' && (env.NEW_RELIC_BROWSER_APP_ID != '' || env.NEXT_PUBLIC_NEW_RELIC_BROWSER_APP_ID != '') }}
        run: pnpm observability:upload-source-maps

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
